### ISSUE TITLE
python setup.py egg_info error

### ISSUE THREAD

**Issue by sebhahn** [blue-yonder/pyscaffold#128]
If I create a new pyscaffold python package and run `python setup.py egg_info` I get the following error message:

```
python setup.py egg_info
Couldn't find index page for 'pyscaffold' (maybe misspelled?)
No local packages or working download links found for pyscaffold<2.6a0,>=2.5a0
Traceback (most recent call last):
  File "setup.py", line 23, in <module>
    setup_package()
  File "setup.py", line 19, in setup_package
    use_pyscaffold=True)
  File "/home/shahn/.pyenv/versions/warp_conda/envs/warp_env/lib/python2.7/distutils/core.py", line 111, in setup
    _setup_distribution = dist = klass(attrs)
  File "/home/shahn/.pyenv/versions/warp_conda/envs/warp_env/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/setuptools/dist.py", line 315, in __init__
  File "/home/shahn/.pyenv/versions/warp_conda/envs/warp_env/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/setuptools/dist.py", line 361, in fetch_build_eggs
  File "/home/shahn/.pyenv/versions/warp_conda/envs/warp_env/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 851, in resolve
  File "/home/shahn/.pyenv/versions/warp_conda/envs/warp_env/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 1123, in best_match
  File "/home/shahn/.pyenv/versions/warp_conda/envs/warp_env/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 1135, in obtain
  File "/home/shahn/.pyenv/versions/warp_conda/envs/warp_env/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/setuptools/dist.py", line 428, in fetch_build_egg
  File "/home/shahn/.pyenv/versions/warp_conda/envs/warp_env/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/setuptools/command/easy_install.py", line 658, in easy_install
distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('pyscaffold<2.6a0,>=2.5a0')
```

Is it a pyscaffold issue or setuptools?

**Comment by sebhahn** [comment]
```
pip install 'pyscaffold<2.6a0,>=2.5a0'
Collecting pyscaffold<2.6a0,>=2.5a0
  Downloading PyScaffold-2.5.8-py2.py3-none-any.whl (363kB)
    100% |████████████████████████████████| 368kB 1.6MB/s 
Requirement already satisfied: six in /home/shahn/warp_conda/envs/warp_env/lib/python2.7/site-packages (from pyscaffold<2.6a0,>=2.5a0)
Installing collected packages: pyscaffold
Successfully installed pyscaffold-2.5.8

```
                                                                                                                                                                                                                                                                                                                                                                                            
```
python setup.py egg_info              
running egg_info
writing test_pyscaffold.egg-info/PKG-INFO
writing top-level names to test_pyscaffold.egg-info/top_level.txt
writing dependency_links to test_pyscaffold.egg-info/dependency_links.txt
[pbr] Reusing existing SOURCES.txt
```

If I install pyscaffold before, it works?

**Comment by sebhahn** [comment]
Nevermind, seems like to be related to my .pydistutils.cfg settings
