### ISSUE TITLE
install fail on windows with python 2.7.2

### ISSUE THREAD

**Issue by fruch** [blue-yonder/pyscaffold#37]
I'm in a virtualenv with python2.7.2
Windows7, under bash (i.e. GitBash)

You are using pip version 6.0.6, however version 6.0.8 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting git+https://github.com/blue-yonder/pyscaffold.git
  Cloning https://github.com/blue-yonder/pyscaffold.git to c:\users\ifruchte\app
data\local\temp\pip-mllxg7-build
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "c:\users\ifruchte\appdata\local\temp\pip-mllxg7-build\setup.py", line 520, in <module>
        setup_package()
      File "c:\users\ifruchte\appdata\local\temp\pip-mllxg7-build\setup.py", line 477, in setup_package
        metadata, console_scripts = read_setup_cfg()
      File "c:\users\ifruchte\appdata\local\temp\pip-mllxg7-build\setup.py", line 166, in read_setup_cfg
        config_file = StringIO(read(os.path.join(__location__, 'setup.cfg')))
    TypeError: initial_value must be unicode or None, not str
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

      File "<string>", line 20, in <module>

      File "c:\users\ifruchte\appdata\local\temp\pip-mllxg7-build\setup.py", line 520, in <module>

        setup_package()

      File "c:\users\ifruchte\appdata\local\temp\pip-mllxg7-build\setup.py", line 477, in setup_package

        metadata, console_scripts = read_setup_cfg()

      File "c:\users\ifruchte\appdata\local\temp\pip-mllxg7-build\setup.py", line 166, in read_setup_cfg

        config_file = StringIO(read(os.path.join(__location__, 'setup.cfg')))

    TypeError: initial_value must be unicode or None, not str

**Comment by FlorianWilhelm** [comment]
Thanks for your feedback. I just tried it with Windows **8**, so not 7 because I don't have access to it. With Windows 8 I created a Virtual Environment, activated it and run `pip install pyscaffold`, followed by `putup my_project` and it worked. I have Python 2.7.8 installed though.
Could you update to Python 2.7.8 just to rule out that your version has an issue?

**Comment by FlorianWilhelm** [comment]
@fruch I might have found the problem and uploaded a new development version. Could you try this:
> pip install -U pyscaffold==2.0.1c1
and report back if it solved your issue? Thanks.

**Comment by fruch** [comment]
Will do

**Comment by fruch** [comment]
yeah this version work correctly

**Comment by FlorianWilhelm** [comment]
Thanks for reporting back
