### ISSUE TITLE
Does not install setuptools>9.0 automatically

### ISSUE THREAD

**Issue by xhochy** [blue-yonder/pyscaffold#63]
Using 2.3rc10, the generated setup.py does not install setuptools>9.0 but rather uses 2.0.2 and then crashes with the following trace (reproduced using pip 1.5.6 and 7.1.0).

```
% pip install -e .                                                                                                                       [10/1518]
Obtaining file://...
    Complete output from command python setup.py egg_info:
    
    Installed /tmp/easy_install-wWfn4d/pyscaffold-2.3rc10/setuptools_scm-1.5.5-py2.7.egg
    Searching for pbr>=1.2,<1.3a0
    Reading https://pypi.python.org/simple/pbr/
    Best match: pbr 1.2.0
    Downloading https://pypi.python.org/packages/source/p/pbr/pbr-1.2.0.tar.gz#md5=b5b93565a5c6fd514889d5f5d83a485b
    Processing pbr-1.2.0.tar.gz
    Writing /tmp/easy_install-wWfn4d/pyscaffold-2.3rc10/temp/easy_install-D7iuwn/pbr-1.2.0/setup.cfg
    Running pbr-1.2.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-wWfn4d/pyscaffold-2.3rc10/temp/easy_install-D7iuwn/pbr-1.2.0/egg-dist-tmp-b7NGrp
    
    Installed /tmp/easy_install-wWfn4d/pyscaffold-2.3rc10/pbr-1.2.0-py2.7.egg
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File ".../setup.py", line 24, in <module>
        setup_package()
      File ".../setup.py", line 20, in setup_package
        use_pyscaffold=True)
      File "/usr/lib/python2.7/distutils/core.py", line 112, in setup
        _setup_distribution = dist = klass(attrs)
      File ".../local/lib/python2.7/site-packages/setuptools/dist.py", line 239, in __init__
        self.fetch_build_eggs(attrs.pop('setup_requires'))
      File ".../local/lib/python2.7/site-packages/setuptools/dist.py", line 263, in fetch_build_eggs
        parse_requirements(requires), installer=self.fetch_build_egg
      File ".../local/lib/python2.7/site-packages/pkg_resources.py", line 563, in resolve
        dist = best[req.key] = env.best_match(req, self, installer)
      File ".../local/lib/python2.7/site-packages/pkg_resources.py", line 801, in best_match
        return self.obtain(req, installer) # try and download/install
      File ".../local/lib/python2.7/site-packages/pkg_resources.py", line 813, in obtain
        return installer(requirement)
      File ".../local/lib/python2.7/site-packages/setuptools/dist.py", line 313, in fetch_build_egg
        return cmd.easy_install(req)
      File ".../local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 593, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File ".../local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 623, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File ".../local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 809, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File ".../local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1015, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File ".../local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1000, in run_setup
        run_setup(setup_script, args)
      File ".../local/lib/python2.7/site-packages/setuptools/sandbox.py", line 50, in run_setup
        lambda: execfile(
      File ".../local/lib/python2.7/site-packages/setuptools/sandbox.py", line 100, in run
        return func()
      File ".../local/lib/python2.7/site-packages/setuptools/sandbox.py", line 52, in <lambda>
        {'__file__':setup_script, '__name__':'__main__'}
      File "setup.py", line 134, in <module>
    
      File "setup.py", line 130, in setup_package
    
      File "/usr/lib/python2.7/distutils/core.py", line 112, in setup
        _setup_distribution = dist = klass(attrs)
      File ".../local/lib/python2.7/site-packages/setuptools/dist.py", line 239, in __init__
        self.fetch_build_eggs(attrs.pop('setup_requires'))
      File ".../local/lib/python2.7/site-packages/setuptools/dist.py", line 263, in fetch_build_eggs
        parse_requirements(requires), installer=self.fetch_build_egg
      File ".../local/lib/python2.7/site-packages/pkg_resources.py", line 575, in resolve
        raise VersionConflict(dist,req) # XXX put more info here
    pkg_resources.VersionConflict: (setuptools 2.0.2 (.../lib/python2.7/site-packages), Requirement.parse('setuptools>=9.0'))
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /...
```

Output of `pip list`:
```
argparse (1.2.1)
pip (1.5.6)
setuptools (2.0.2)
wsgiref (0.1.2)
```

**Comment by FlorianWilhelm** [comment]
After some long discussions on IRC and web searches, I come to the conclusion that it is just not possible due to some limitations of setuptools and pip. So the best way is to remove setuptools from the requirements and let it fail late with a nice error message. [Ronny Pfannschmidt](https://github.com/RonnyPfannschmidt), maintainer of setuptools_scm and contributor to setuptools, found no robust way to install a minimum version of setuptools. So as of now this seems to be a wontfix.

**Comment by FlorianWilhelm** [comment]
Removed setuptools from requirements. User will see the warning of setuptools_scm about setuptools beeing too old. See commit e8cbcebb0fcad8a7dee65739c21ca767e5ad91fa.
