### ISSUE TITLE
2.4.3 broken?

### ISSUE THREAD

**Issue by sebastianneubauer** [blue-yonder/pyscaffold#80]
I get an exception when I try to create a new package with `putpup new_package` since the new version 2.4.3, 2.4.2 works fine:
```
Traceback (most recent call last):
  File "/bin/putup", line 11, in <module>
    sys.exit(run())
  File "local/lib/python2.7/site-packages/pyscaffold/shell.py", line 54, in func_wrapper
    func(*args, **kwargs)
  File "local/lib/python2.7/site-packages/pyscaffold/utils.py", line 102, in func_wrapper
    func(*args, **kwargs)
  File "local/lib/python2.7/site-packages/pyscaffold/cli.py", line 257, in run
    main(sys.argv[1:])
  File "local/lib/python2.7/site-packages/pyscaffold/cli.py", line 243, in main
    create_project(opts)
  File "local/lib/python2.7/site-packages/pyscaffold/cli.py", line 206, in create_project
    proj_struct = structure.make_structure(opts)
  File "local/lib/python2.7/site-packages/pyscaffold/structure.py", line 62, in make_structure
    'skeleton.py': templates.skeleton(opts)},
  File "local/lib/python2.7/site-packages/pyscaffold/templates/__init__.py", line 298, in skeleton
    return template.substitute(opts)
  File "/usr/lib/python2.7/string.py", line 172, in substitute
    return self.pattern.sub(convert, self.template)
  File "/usr/lib/python2.7/string.py", line 162, in convert
    val = mapping[named]
KeyError: u'namespace_pkg'
```

My environment:
```
pip list
pbr (1.8.1)
pip (7.1.2)
pyscaffold (2.4.3)
setuptools (18.4)
setuptools-scm (1.8.0)
six (1.10.0)
```

**Comment by FlorianWilhelm** [comment]
Sorry for that, seems to be a corrupt upload to PyPI, at least that explains why all unittests were green. I uploaded a version 2.4.4 but it seems to take a while until it spreads through all caches. Could you check it in about an hour if it works for you?
