### ISSUE TITLE
Installation Error on Windows

### ISSUE THREAD

**Issue by cpaulik** [blue-yonder/pyscaffold#90]
When trying to install my [pygeogrids](https://github.com/TUW-GEO/pygeogrids) package on Windows I get the following error:

```
Collecting pygeogrids
  Downloading pygeogrids-0.1.9.tar.gz
    Complete output from command python setup.py egg_info:
    no previously-included directories found matching 'documentation\_build'
    zip_safe flag not set; analyzing archive contents...
    six: module references __path__

    Installed c:\users\cpa\appdata\local\temp\easy_install-sqim5d\pyscaffold-2.5.5b1\.eggs\six-1.10.0-py2.7.egg
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\cpa\appdata\local\temp\pip-build-wbair0\pygeogrids\setup.py", line 23, in <module>
        setup_package()
      File "c:\users\cpa\appdata\local\temp\pip-build-wbair0\pygeogrids\setup.py", line 19, in setup_package
        use_pyscaffold=True)
      File "C:\Users\cpa\AppData\Local\Continuum\Anaconda3\envs\test-rsdata\lib\distutils\core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "C:\Users\cpa\AppData\Local\Continuum\Anaconda3\envs\test-rsdata\lib\site-packages\setuptools-20.1.1-py2.7.egg\setuptools
\dist.py", line 269, in __init__
      File "C:\Users\cpa\AppData\Local\Continuum\Anaconda3\envs\test-rsdata\lib\site-packages\setuptools-20.1.1-py2.7.egg\setuptools
\dist.py", line 313, in fetch_build_eggs
      File "C:\Users\cpa\AppData\Local\Continuum\Anaconda3\envs\test-rsdata\lib\site-packages\setuptools-20.1.1-py2.7.egg\pkg_resour
ces\__init__.py", line 825, in resolve
      File "C:\Users\cpa\AppData\Local\Continuum\Anaconda3\envs\test-rsdata\lib\site-packages\setuptools-20.1.1-py2.7.egg\pkg_resour
ces\__init__.py", line 1070, in best_match
      File "C:\Users\cpa\AppData\Local\Continuum\Anaconda3\envs\test-rsdata\lib\site-packages\setuptools-20.1.1-py2.7.egg\pkg_resour
ces\__init__.py", line 1082, in obtain
      File "C:\Users\cpa\AppData\Local\Continuum\Anaconda3\envs\test-rsdata\lib\site-packages\setuptools-20.1.1-py2.7.egg\setuptools
\dist.py", line 380, in fetch_build_egg
      File "C:\Users\cpa\AppData\Local\Continuum\Anaconda3\envs\test-rsdata\lib\site-packages\setuptools-20.1.1-py2.7.egg\setuptools
\command\easy_install.py", line 640, in easy_install
      File "C:\Users\cpa\AppData\Local\Continuum\Anaconda3\envs\test-rsdata\lib\site-packages\setuptools-20.1.1-py2.7.egg\setuptools
\command\easy_install.py", line 670, in install_item
      File "C:\Users\cpa\AppData\Local\Continuum\Anaconda3\envs\test-rsdata\lib\site-packages\setuptools-20.1.1-py2.7.egg\setuptools
\command\easy_install.py", line 853, in install_eggs
      File "C:\Users\cpa\AppData\Local\Continuum\Anaconda3\envs\test-rsdata\lib\site-packages\setuptools-20.1.1-py2.7.egg\setuptools
\command\easy_install.py", line 1081, in build_and_install
      File "C:\Users\cpa\AppData\Local\Continuum\Anaconda3\envs\test-rsdata\lib\site-packages\setuptools-20.1.1-py2.7.egg\setuptools
\command\easy_install.py", line 1067, in run_setup
      File "C:\Users\cpa\AppData\Local\Continuum\Anaconda3\envs\test-rsdata\lib\site-packages\setuptools-20.1.1-py2.7.egg\setuptools
\sandbox.py", line 246, in run_setup
      File "C:\Users\cpa\AppData\Local\Continuum\Anaconda3\envs\test-rsdata\lib\contextlib.py", line 35, in __exit__
        self.gen.throw(type, value, traceback)
      File "C:\Users\cpa\AppData\Local\Continuum\Anaconda3\envs\test-rsdata\lib\site-packages\setuptools-20.1.1-py2.7.egg\setuptools
\sandbox.py", line 195, in setup_context
      File "C:\Users\cpa\AppData\Local\Continuum\Anaconda3\envs\test-rsdata\lib\contextlib.py", line 35, in __exit__
        self.gen.throw(type, value, traceback)
      File "C:\Users\cpa\AppData\Local\Continuum\Anaconda3\envs\test-rsdata\lib\site-packages\setuptools-20.1.1-py2.7.egg\setuptools
\sandbox.py", line 166, in save_modules
      File "C:\Users\cpa\AppData\Local\Continuum\Anaconda3\envs\test-rsdata\lib\site-packages\setuptools-20.1.1-py2.7.egg\setuptools
\sandbox.py", line 141, in resume
      File "C:\Users\cpa\AppData\Local\Continuum\Anaconda3\envs\test-rsdata\lib\site-packages\setuptools-20.1.1-py2.7.egg\setuptools
\sandbox.py", line 154, in save_modules
      File "C:\Users\cpa\AppData\Local\Continuum\Anaconda3\envs\test-rsdata\lib\site-packages\setuptools-20.1.1-py2.7.egg\setuptools
\sandbox.py", line 195, in setup_context
      File "C:\Users\cpa\AppData\Local\Continuum\Anaconda3\envs\test-rsdata\lib\site-packages\setuptools-20.1.1-py2.7.egg\setuptools
\sandbox.py", line 243, in run_setup
      File "C:\Users\cpa\AppData\Local\Continuum\Anaconda3\envs\test-rsdata\lib\site-packages\setuptools-20.1.1-py2.7.egg\setuptools
\sandbox.py", line 273, in run
      File "C:\Users\cpa\AppData\Local\Continuum\Anaconda3\envs\test-rsdata\lib\site-packages\setuptools-20.1.1-py2.7.egg\setuptools
\sandbox.py", line 242, in runner
      File "C:\Users\cpa\AppData\Local\Continuum\Anaconda3\envs\test-rsdata\lib\site-packages\setuptools-20.1.1-py2.7.egg\setuptools
\sandbox.py", line 46, in _execfile
      File "c:\users\cpa\appdata\local\temp\easy_install-sqim5d\PyScaffold-2.5.5b1\setup.py", line 27, in <module>

      File "c:\users\cpa\appdata\local\temp\easy_install-sqim5d\PyScaffold-2.5.5b1\setup.py", line 23, in setup_package
        setup_package()
      File "C:\Users\cpa\AppData\Local\Continuum\Anaconda3\envs\test-rsdata\lib\distutils\core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "c:\users\cpa\appdata\local\continuum\anaconda3\envs\test-rsdata\lib\site-packages\setuptools-20.1.1-py2.7.egg\setuptools
\dist.py", line 272, in __init__
      File "C:\Users\cpa\AppData\Local\Continuum\Anaconda3\envs\test-rsdata\lib\distutils\dist.py", line 287, in __init__
        self.finalize_options()
      File "c:\users\cpa\appdata\local\continuum\anaconda3\envs\test-rsdata\lib\site-packages\setuptools-20.1.1-py2.7.egg\setuptools
\dist.py", line 327, in finalize_options
      File "c:\users\cpa\appdata\local\temp\easy_install-sqim5d\PyScaffold-2.5.5b1\pyscaffold\integration.py", line 106, in pyscaffo
ld_keyword
      File "c:\users\cpa\appdata\local\temp\easy_install-sqim5d\PyScaffold-2.5.5b1\pyscaffold\repo.py", line 88, in get_git_root
    TypeError: 'NoneType' object is not callable
```

This happens when all the dependencies are already installed manually. The same package works without problems in Linux.

**Comment by cpaulik** [comment]
Oh, can this be because git is not installed on the target system?

**Comment by FlorianWilhelm** [comment]
Hi @cpaulik, what exactly did you do to install it? Did you use pip? Please be more precise. If you used ``python setup.py sdist`` or  ``python setup.py bdist_wheel`` the resulting package should have no dependency on PyScaffold at all. That's the idea, you only need PyScaffold (and git) during the development but not when someone wants to use your package. This is why I assume you used ``python setup.py install`` to install it?

**Comment by cpaulik** [comment]
I used `pip install pygeogrids` which loaded the source distribution from https://pypi.python.org/pypi/pygeogrids/0.1.9

I'll check the tar file again since I guess there is something wrong on my side.

**Comment by cpaulik** [comment]
Ok. I've run `python setup.py sdist` on my Ubuntu machine on the latest `master` of [pygeogrids](https://github.com/TUW-GEO/pygeogrids). This gave me `pygeogrids-0.1.9.post0.dev3+g8f0858b.tar.gz`.

Then I ran `pip install "H:\pygeogrids-0.1.9.post0.dev3+g8f0858b.tar.gz"` on my Windows machine which gave the same error as in the original post.

Do you have any ideas why this could be?.

The [setup.py](https://github.com/TUW-GEO/pygeogrids/blob/master/setup.py) and [setup.cfg](https://github.com/TUW-GEO/pygeogrids/blob/master/setup.cfg) look like the pyscaffold templates.

**Comment by cpaulik** [comment]
This is the conda environment in which I am trying all of this:
```
mkl                       11.3.1                        0
msvc_runtime              1.0.1                     vc9_0
netcdf4                   1.2.2               np110py27_0
numpy                     1.10.4                   py27_0
pip                       8.0.2                    py27_0
proj.4                    4.9.1                         0
pygeogrids                0.1.5                     <pip>
pyproj                    1.9.4                    py27_1
python                    2.7.11                        2
setuptools                20.1.1                   py27_0
wheel                     0.29.0                   py27_0
```

**Comment by FlorianWilhelm** [comment]
@cpaulik You may have found a serious bug in PyScaffold. I could reproduce it and I think I know where the problem is. Give me some more time, I'll fix it asap.

**Comment by FlorianWilhelm** [comment]
@cpaulik Could you check if you have the same problem with PyScaffold 2.5.5? Maybe you need to remove manually older version of PyScaffold first.

**Comment by cpaulik** [comment]
Thanks. I can now install the existing package as well as newly generated ones.
